### ISSUE TITLE
Could you share me the LRS2-BBC and LRS3-TED dataset? Thank you very much!

### ISSUE THREAD

**Issue by MPQZF** [david-gimeno/lipreading-thesis#1]

**Comment by david-gimeno** [comment]
No. These datasets must be downloaded according to the original author's conditions. Here you can find the datasets and the instructions to download them:

https://www.robots.ox.ac.uk/~vgg/data/lip_reading/

Subsequent questions about how to prepare the data to make my code work can be ask in a different issue. Thanks.
